### ISSUE TITLE
[library] Create a library folder in submitty

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#28] opened 2019-10-11 02:41 UTC
**What problem are you trying to solve with Submitty**
Update the install process to create a folder for the library. The submitty user should have full control of this folder. 

**Describe the way you'd like to solve this problem**
The process may only be updates to the install documentation. Only if it can not be automated.

**Comment by sballance** [comment] 2019-11-04 04:34
I'm closing this as it is a duplicate of #92

**Comment by sballance** [comment] 2019-11-04 04:45
Closed on accident. Re-opening until the pull request gets merged.

**Comment by dakriy** [comment] 2019-11-06 06:22
Done with #92

**Closed by dakriy** 2019-11-06 06:22 UTC
Labels: Backend, admin
