### ISSUE TITLE
[Admin] [Back] develop git implementation

### ISSUE THREAD

**Issue by lucasmarcondes** [wwu-cs/Submitty#76] opened 2019-10-29 01:57 UTC
#67 must be completed first.

We want to be able to access the Github specified folder and display the folder contents.

**Comment by dakriy** [comment] 2019-11-08 21:08
Why is this admin? This seems like an instructor issue.

**Comment by dakriy** [comment] 2019-11-15 00:38
Ok I think this is a duplicate of #72 since it seems to have depended on #67 which was completed and the backend is currently under review. So I'm gonna close this. If it shouldn't have been close please open a new more specific issue.

**Closed by dakriy** 2019-11-15 00:38 UTC
Labels: Backend, admin
