### ISSUE TITLE
Implement git actions for library upload form

### ISSUE THREAD

**Issue by mwilde1998** [wwu-cs/Submitty#70] opened 2019-10-25 16:53 UTC
**What problem are you trying to solve with Submitty**
Complete the backend save action of the git form for the homework library.

**Comment by mwilde1998** [comment] 2019-10-26 03:20
If anyone knows or understands more about this issue and knows how to better explain it, please add to it.

**Comment by dakriy** [comment] 2019-11-15 00:32
Seems like a duplicate of #72 which is a subset of #89 So... Closing.

**Closed by dakriy** 2019-11-15 00:32 UTC
Labels: Backend
